name: Generate Pixel Muneco

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Pillow
        run: pip install pillow

      - name: Run pixel muneco script
        run: python scripts/muneco_pixel.py

      - name: Commit GIF
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add assets/muneco_pixel_final.gif
          git commit -m "update muneco_pixel_final.gif" || echo "no changes"
          git push
