name: Generate Banner

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install pillow
      - name: Run banner script
        run: python scripts/banner.py
      - name: Commit banner
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add assets/banner.gif
          git commit -m "update banner" || echo "no changes"
          git push
