name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ssalazaro8
          outputs: |
            dist/snake.svg

      - name: Move snake to assets
        run: |
          mkdir -p assets
          mv dist/snake.svg assets/snake.svg

      - name: Commit snake
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add assets/snake.svg
          git commit -m "update snake" || echo "no changes"
          git push
